version: '3.8'
services:
  php:
    build: .
    container_name: dailywag_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dailywag_db
    environment:
      MYSQL_USER: testuser
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: dailywag
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    platform: linux/arm64
    container_name: dailywag_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8082:80"
    depends_on:
      - db