version: '3.8'
services:
  php:
    build: .
    container_name: dailywag_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dailywag_db
    environment:
      MYSQL_USER: samyuktha
      MYSQL_ROOT_PASSWORD: samyupass
      MYSQL_DATABASE: dailywag_db
    ports:
      - "3306:3306"
    volumes:
      - ./src/init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dailywag_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: samyuktha
      MYSQL_ROOT_PASSWORD: samyupass
    ports:
      - "8082:80"
    depends_on:
      - db