version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: dailywag_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: dailywag
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dailywag_php
    volumes:
      - ./public:/var/www/html
      - ./api:/var/www/api
      - ./src:/var/www/src
    ports:
      - "8000:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dailywag_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_USER: testuser
      PMA_PASSWORD: testpassword
    ports:
      - "8082:80"
    depends_on:
      - db
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ../daily-wag-frontend:/app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - php



